name: Add redirect/shortner
description: add new redirect/shortner to https://msnehulak.github.io/r/
labels:
- issue_worker
body:
- type: input
  id: link
  attributes:
    label: Web link
    description: Link to the web
    placeholder: https://msnehulak.github.io/
  validations:
    required: true

- type: input
  id: name
  attributes:
    label: Name of redirect
    description: Name of redirect
    placeholder: Youtube, Discord
  validations:
    required: true

- type: input
  id: redirect 
  attributes:
    label: Redirect
    description: what is going to be after r/XX
    placeholder: yt, dc
  validations:
    required: true

