name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: read
  deployments: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Load repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Python
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.6'

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      # Web Build (Pelican)
      - name: Build Web Site
        env:
          OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
          OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SITEURL: https://snehulak.dev
        run: |
          pelican content -s publishconf.py

      # Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v3.5.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: './output' # Výstupní složka Pelicanu
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'preview' }}
