name: Deploy Web & Redirects

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      
      - 'bash/**'
      - '.env.example'
      - '.lighthouserc.json'
      
      - '.github/.FUNDING.yml'
      - '.gitignore'
      - '.gitattributes'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      is_production:
        description: 'Nasadit do PRODUKCE?'
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  deployments: write
  pull-requests: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Cache cache/ folder 
        id: cache-custom
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-custom-${{ hashFiles('config.json') }}
          restore-keys: |
            ${{ runner.os }}-custom-

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Build Web Site
        env:
          OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
          OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          STEAM_API: ${{ secrets.STEAM_API }}
          
          SITEURL: ${{ (github.event_name == 'push' || github.event_name == 'schedule' || inputs.is_production == true) && vars.SITE_URL || vars.PREVIEW_SITE_URL }}
        run: |
          pelican content -s publishconf.py

      - name: Gitingest{{ AUTHOR }}
        run: |
          chmod +x bash/gitingest.sh
          ./bash/gitingest.sh

      - name: Upload Cloudflare Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-output
          path: './output'

      - name: Upload GitHub Redirects Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './redirect'

  deploy-cloudflare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Cloudflare Artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudflare-output
          path: './output'

      - name: Deploy to Cloudflare Pages via Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.is_production }}" = "false" ]; then
            TARGET_BRANCH="preview"
          else
            TARGET_BRANCH="main"
          fi

          npx wrangler pages deploy ./output --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=$TARGET_BRANCH

  deploy-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages as redirects
        id: deployment
        uses: actions/deploy-pages@v4

