name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

      # Load repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.6'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Web Build
      - name: Build Web Site
        env:
          OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
          OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SITEURL: https://msnehulak.github.io
        run: |
          pelican content -s publishconf.py

      # Web publish
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Commit
#      - name: Commit and push changes
#        run: |
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git add content/en/osu.md content/cs/osu.md content/de/osu.md
#          git commit -m "Web update [skip ci]" || exit 0
#          git push
