name: Issue Form Worker

on:
  issues:
    types: [opened, edited]

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'issue_worker')

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      # clone repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set-Up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install Libarys
      - name: Install dependencies
        run: pip install -r requirements.txt
    
      # Format form to json
      - name: Format issue form to json
        id: parse_form
        uses: peter-murray/issue-forms-body-parser@v4
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'

      # Run pythonn
      - name: Parse Issue and Generate JSON
        env:
          ISSUE_JSON: ${{ steps.parse_form.outputs.payload }}
        run: python code/issueworker.py

        # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Issue Worker commit #${{ github.event.issue.number }}"
          branch: "issue_worker/issue-${{ github.event.issue.number }}"
          title: "Worker start form Issue #${{ github.event.issue.number }}"
          body: |
            This pull requests is automated generated form issue forms.

            Issue body:
            ${{ github.event.issue.body }}
          labels: |
            automated-pr
            data-update
