name: Auto Create PR from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  create-pr:
    # Workflow se spustí pouze tehdy, pokud má Issue správný nadpis nebo label
    # Doporučuji v novém formuláři (yaml) nastavit fixní label, např. "new-character"
    if: contains(github.event.issue.labels.*.name, 'issue_worker')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      # 1. Klonování repozitáře
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Nastavení Pythonu
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install markdown

      # 3. Spuštění parsovacího skriptu s předáním textu z Issue
      - name: Parse Issue and Generate JSON
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: python code/issueworker.py

      # 4. Vytvoření Pull Requestu pomocí hotové akce
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Issue Worker commit #${{ github.event.issue.number }}"
          branch: "issue_worker/issue-${{ github.event.issue.number }}"
          title: "Worker start form Issue #${{ github.event.issue.number }}"
          body: |
            This pull requests is automated generated form issue forms.

            Issue body:
            ${{ github.event.issue.body }}
          labels: |
            automated-pr
            data-update
